<?php
/**
 * @author Hervé Guétin <www.linkedin.com/in/herveguetin>
 */ ?>
<?php
/** @var \Magento\Framework\View\Element\Template $block */
?>
    <div x-data="Zermatt.Module('Demo_QuickSearch')">
        <div class="content">
            <div x-show="!loading && results.length > 0" class="results">
                <template x-for="product in results">
                    <article class="product">
                        <img :src="product.thumbnail" :alt="product.title" class="thumbnail" width="80" height="80"/>
                        <div class="info">
                            <div x-text="product.title"></div>
                        </div>
                    </article>
                </template>
            </div>
            <div x-show="loading" class="loader"></div>
            <p x-show="!query"><?= __('Please search a product in the header search. Ex: phone, samsung, food, vegetables, ...') ?></p>
            <p x-show="!loading && query && results.length === 0"><?= __('No result.') ?></p>
        </div>
    </div>
